/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as GestaoRouteImport } from './routes/gestao'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as PecasIndexRouteImport } from './routes/pecas.index'
import { Route as PecasIdRouteImport } from './routes/pecas.$id'
import { Route as ApiPublicWebhooksKiwifyRouteImport } from './routes/api/public/webhooks/kiwify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const GestaoRoute = GestaoRouteImport.update({
  id: '/gestao',
  path: '/gestao',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PecasIndexRoute = PecasIndexRouteImport.update({
  id: '/pecas/',
  path: '/pecas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PecasIdRoute = PecasIdRouteImport.update({
  id: '/pecas/$id',
  path: '/pecas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksKiwifyRoute = ApiPublicWebhooksKiwifyRouteImport.update({
  id: '/api/public/webhooks/kiwify',
  path: '/api/public/webhooks/kiwify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/assinatura': typeof AssinaturaRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/entrar': typeof EntrarRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/gestao': typeof GestaoRoute
  '/painel': typeof PainelRoute
  '/vendas': typeof VendasRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pecas/$id': typeof PecasIdRoute
  '/pecas/': typeof PecasIndexRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/assinatura': typeof AssinaturaRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/entrar': typeof EntrarRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/gestao': typeof GestaoRoute
  '/painel': typeof PainelRoute
  '/vendas': typeof VendasRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pecas/$id': typeof PecasIdRoute
  '/pecas': typeof PecasIndexRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/assinatura': typeof AssinaturaRoute
  '/catalogo': typeof CatalogoRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/entrar': typeof EntrarRoute
  '/estoque': typeof EstoqueRoute
  '/financeiro': typeof FinanceiroRoute
  '/gestao': typeof GestaoRoute
  '/painel': typeof PainelRoute
  '/vendas': typeof VendasRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pecas/$id': typeof PecasIdRoute
  '/pecas/': typeof PecasIndexRoute
  '/api/public/webhooks/kiwify': typeof ApiPublicWebhooksKiwifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/assinatura'
    | '/catalogo'
    | '/clientes'
    | '/compras'
    | '/entrar'
    | '/estoque'
    | '/financeiro'
    | '/gestao'
    | '/painel'
    | '/vendas'
    | '/loja/$slug'
    | '/pecas/$id'
    | '/pecas/'
    | '/api/public/webhooks/kiwify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/assinatura'
    | '/catalogo'
    | '/clientes'
    | '/compras'
    | '/entrar'
    | '/estoque'
    | '/financeiro'
    | '/gestao'
    | '/painel'
    | '/vendas'
    | '/loja/$slug'
    | '/pecas/$id'
    | '/pecas'
    | '/api/public/webhooks/kiwify'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/assinatura'
    | '/catalogo'
    | '/clientes'
    | '/compras'
    | '/entrar'
    | '/estoque'
    | '/financeiro'
    | '/gestao'
    | '/painel'
    | '/vendas'
    | '/loja/$slug'
    | '/pecas/$id'
    | '/pecas/'
    | '/api/public/webhooks/kiwify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  AssinaturaRoute: typeof AssinaturaRoute
  CatalogoRoute: typeof CatalogoRoute
  ClientesRoute: typeof ClientesRoute
  ComprasRoute: typeof ComprasRoute
  EntrarRoute: typeof EntrarRoute
  EstoqueRoute: typeof EstoqueRoute
  FinanceiroRoute: typeof FinanceiroRoute
  GestaoRoute: typeof GestaoRoute
  PainelRoute: typeof PainelRoute
  VendasRoute: typeof VendasRoute
  LojaSlugRoute: typeof LojaSlugRoute
  PecasIdRoute: typeof PecasIdRoute
  PecasIndexRoute: typeof PecasIndexRoute
  ApiPublicWebhooksKiwifyRoute: typeof ApiPublicWebhooksKiwifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pecas/': {
      id: '/pecas/'
      path: '/pecas'
      fullPath: '/pecas/'
      preLoaderRoute: typeof PecasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pecas/$id': {
      id: '/pecas/$id'
      path: '/pecas/$id'
      fullPath: '/pecas/$id'
      preLoaderRoute: typeof PecasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/kiwify': {
      id: '/api/public/webhooks/kiwify'
      path: '/api/public/webhooks/kiwify'
      fullPath: '/api/public/webhooks/kiwify'
      preLoaderRoute: typeof ApiPublicWebhooksKiwifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  AssinaturaRoute: AssinaturaRoute,
  CatalogoRoute: CatalogoRoute,
  ClientesRoute: ClientesRoute,
  ComprasRoute: ComprasRoute,
  EntrarRoute: EntrarRoute,
  EstoqueRoute: EstoqueRoute,
  FinanceiroRoute: FinanceiroRoute,
  GestaoRoute: GestaoRoute,
  PainelRoute: PainelRoute,
  VendasRoute: VendasRoute,
  LojaSlugRoute: LojaSlugRoute,
  PecasIdRoute: PecasIdRoute,
  PecasIndexRoute: PecasIndexRoute,
  ApiPublicWebhooksKiwifyRoute: ApiPublicWebhooksKiwifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
